enum CartStatus {
    ACTIVE
    CHECKED_OUT
    ABANDONED
}

type Cart implements AuditableEntity {
    id: ID!
    userId: ID!
    status: CartStatus!
    items: [CartItem!]!
    totalItems: Int!
    createdAt: String!
    updatedAt: String!
    checkedOutAt: String
}

type CartItem implements AuditableEntity {
    id: ID!
    productId: ID!
    quantity: Int!
    createdAt: String!
    updatedAt: String!
}

input AddItemToCartInput {
    productId: ID!
    quantity: Int!
}

# Carts Queries
extend type Query {
    currentUserCart: Cart
}

# Carts Mutations
extend type Mutation {
    addItemToCart(input: AddItemToCartInput!): Cart!
    updateCartItemQuantity(cartItemId: ID!, quantity: Int!): Cart!
    removeItemFromCart(cartItemId: ID!): Cart!
}
