enum OrderStatus {
    PENDING
    PAID
    CANCELLED
}

enum PaymentStatus {
    PENDING
    SUCCEEDED
    FAILED
}

enum WebhookStatus {
    RECEIVED
    PROCESSED
    FAILED
}

type Order implements AuditableEntity {
    id: ID!
    userId: ID!
    cartId: ID
    addressId: ID!
    discountId: ID
    status: OrderStatus!
    totalAmount: Money!
    discountAmount: Money!
    items: [OrderItem!]!
    address: Address!
    discount: Discount
    payment: Payment
    createdAt: DateTime!
    updatedAt: DateTime!
}

type OrderItem {
    id: ID!
    orderId: ID!
    productId: ID!
    priceAtPurchase: Money!
    quantity: Int!
}

type Payment {
    id: ID!
    orderId: ID!
    stripePaymentIntentId: String!
    status: PaymentStatus!
    amount: Money!
    createdAt: DateTime!
}

type PaymentIntentResponse {
    clientSecret: String!
    paymentIntentId: String!
}

type WebhookResponse {
    status: String!
    message: String
}

type StripeWebhook {
    id: ID!
    paymentId: ID
    stripeEventId: String!
    eventType: String!
    payload: String!
    status: WebhookStatus!
    receivedAt: DateTime!
    processedAt: DateTime
}

type Discount {
    id: ID!
    code: String!
    percentage: Int!
    startDate: DateTime!
    endDate: DateTime!
    isActive: Boolean!
    createdAt: DateTime!
}

input CreateDiscountInput {
    code: String!
    percentage: Int!
    startDate: DateTime!
    endDate: DateTime!
}

extend type Query {
    # If a manager requests orders, they can see all orders, otherwise users can see only their own
    orders(userId: ID): [Order!]! @auth
    discount(code: String!): Discount
    # This query is managed also by logic business to fetch active discounts
    activeDiscounts: [Discount!]!
}

extend type Mutation {
    # Modifying orders or creating carts should be done only by clients (Managers could also do it, but for simplicity we restrict it to clients)
    createOrderFromCart(userId: ID!, addressId: ID!): Order! @auth(role: "ROLE_CLIENT")
    applyDiscountToOrder(orderId: ID!, discountCode: String!): Order! @auth(role: "ROLE_CLIENT")
    removeDiscountFromOrder(orderId: ID!): Order! @auth(role: "ROLE_CLIENT")
    cancelOrder(orderId: ID!): Order! @auth
    createPaymentIntent(orderId: ID!): PaymentIntentResponse! @auth
    handleStripeWebhook(payload: String!, signature: String!, timestamp: String!): WebhookResponse! # No auth needed, signature is verified internally
    createDiscount(input: CreateDiscountInput!): Discount! @auth(role: "ROLE_MANAGER")
    deactivateDiscount(id: ID!): Discount! @auth(role: "ROLE_MANAGER")
}

extend type Subscription {
    # Once order is created/ updated, user is notified
    orderCreated(userId: ID): Order! @auth
    orderStatusUpdated(userId: ID, orderId: ID): Order! @auth
}

