input ProductFilterInput {
    categoryId: ID
    minPrice: Float
    maxPrice: Float
    isActive: Boolean
    search: String
    inStock: Boolean
}

input ProductSortInput {
    field: ProductSortField!
    direction: SortDirection = ASC
}

input CreateProductInput {
    name: String!
    description: String
    price: Float!
    stock: Int!
    categoryIds: [ID!]
    images: [Upload!]
}

input UpdateProductInput {
    name: String
    description: String
    price: Float
    stock: Int
    isActive: Boolean
}

input CreateCategoryInput {
    name: String!
}

input UpdateCategoryInput {
    name: String!
}
