type Query {
    # If a manager requests orders, they can see all orders, otherwise users can see only their own
    orders(userId: ID): [Order!]! @auth
    discount(code: String!): Discount
    # This query is managed also by logic business to fetch active discounts
    activeDiscounts: [Discount!]!
    addresses(userId: ID!): [Address!]! @auth
    address(id: ID!): Address @auth
}

type Mutation {
    # Modifying orders or creating carts should be done only by clients (Managers could also do it, but for simplicity we restrict it to clients)
    createOrderFromCart(userId: ID!, addressId: ID!): Order! @auth(role: "ROLE_CLIENT")
    applyDiscountToOrder(orderId: ID!, discountCode: String!): Order! @auth(role: "ROLE_CLIENT")
    removeDiscountFromOrder(orderId: ID!): Order! @auth(role: "ROLE_CLIENT")
    cancelOrder(orderId: ID!): Order! @auth
    createPaymentIntent(orderId: ID!): PaymentIntentResponse! @auth
    handleStripeWebhook(payload: String!, signature: String!, timestamp: String!): WebhookResponse! # No auth needed, signature is verified internally
    createAddress(userId: ID!, input: CreateAddressInput!): Address! @auth
    updateAddress(id: ID!, input: CreateAddressInput!): Address! @auth
    deleteAddress(id: ID!): Boolean! @auth
    setDefaultAddress(userId: ID!, addressId: ID!): Address! @auth
    createDiscount(input: CreateDiscountInput!): Discount! @auth(role: "ROLE_MANAGER")
    deactivateDiscount(id: ID!): Discount! @auth(role: "ROLE_MANAGER")
}
