enum CartStatus {
    ACTIVE
    CHECKED_OUT
    ABANDONED
}

type Cart implements AuditableEntity {
    id: ID!
    userId: ID!
    status: CartStatus!
    items: [CartItem!]!
    totalItems: Int!
    createdAt: DateTime!
    updatedAt: DateTime!
    checkedOutAt: DateTime
}

type CartItem implements AuditableEntity {
    id: ID!
    productId: ID!
    quantity: Int!
    createdAt: DateTime!
    updatedAt: DateTime!
}

input AddItemToCartInput {
    productId: ID!
    quantity: Int!
}

extend type Query {
    cart(userId: ID!): Cart @auth
}

extend type Mutation {
    addItemToCart(userId: ID!, input: AddItemToCartInput!): Cart! @auth
    updateCartItemQuantity(userId: ID!, cartItemId: ID!, quantity: Int!): Cart! @auth
    removeItemFromCart(userId: ID!, cartItemId: ID!): Cart! @auth
    updateCartStatus(cartId: ID!, status: CartStatus!): Cart! @auth
}

extend type Subscription {
    cartStatusChanged(cartId: ID!): Cart! @auth
}

